title: awesomeosep
description: portfolio
remote_theme: jekyll/minima@d4d779a
author:
   name: awesomeosep
   email: your-email@domain.com
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
   nav_pages:
     - about.md
     - index.md
   social_links:
     - title: About me on Github
       icon: github
       url: "https://github.com/awesomeosep"
